PUT http://localhost:8080/events/2
content-type: application/json

{
    "name": "Test event 3",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2024-06-06T15:30:00.000Z",
}